DROP TABLE IF EXISTS authors;
CREATE TABLE authors(ID UUID PRIMARY KEY, NAME VARCHAR(255));

DROP TABLE IF EXISTS book_authors;
CREATE TABLE book_authors(ID BIGSERIAL PRIMARY KEY, book_id UUID, author_id UUID);

DROP TABLE IF EXISTS books;
CREATE TABLE books(ID UUID PRIMARY KEY, NAME VARCHAR(255));

DROP TABLE IF EXISTS book_genres;
CREATE TABLE book_genres(ID BIGSERIAL PRIMARY KEY, book_Id UUID , genre_Id UUID);

DROP TABLE IF EXISTS genres;
CREATE TABLE genres(ID UUID PRIMARY KEY, NAME VARCHAR(255));

DROP TABLE IF EXISTS my_books;
CREATE TABLE my_books(id BIGSERIAL PRIMARY KEY, my_book_id UUID);