spring:
  datasources:
    url: jdbc:h2:mem:den_db
    username: denis
    password: 123
    driver-class-name: org.h2.Driver
    initialization-mode: always
    schema: schema2.sql
    data: data2.sql

