spring:
  data:
    mongodb:
      database: user_db

mongock:
  #runner-type: "ApplicationRunner" # default
  runner-type: "InitializingBean"
  change-logs-scan-package: ru.chaban.mongock.changelog

    #show-sql: true