spring:
  data:
    mongodb:
      authentication-database: none
      database: user_db
      port: 27017
      host: localhost

mongock:
  runner-type: "ApplicationRunner" # default
  #runner-type: "InitializingBean"
  change-logs-scan-package: ru.chaban.mongock.changelog

    show-sql: true